-- 코드를 작성해주세요
/*
자식의 수?
PARENT_ID가 나 라면 그게 자식이다.

*/


SELECT D.ID, COALESCE(R.CHILD_COUNT, 0)  AS CHILD_COUNT
FROM ECOLI_DATA D
LEFT JOIN
    (SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
     ) R ON R.PARENT_ID = D.ID
ORDER BY ID ASC
