WITH CAR_FEE AS (
    SELECT C.CAR_ID,
    C.CAR_TYPE,
    (30 * C.DAILY_FEE) *
    (100 - REPLACE(P.DISCOUNT_RATE, '%', '')) / 100 AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
        ON C.CAR_TYPE = P.CAR_TYPE  
        AND P.DURATION_TYPE = '30일 이상'
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
        AND NOT EXISTS ( 
          SELECT 1
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
          WHERE H.CAR_ID = C.CAR_ID
                AND H.START_DATE <= DATE '2022-11-30'
                AND H.END_DATE >= DATE '2022-11-01'
    )
)

SELECT *
FROM CAR_FEE
WHERE FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC