-- 코드를 입력하세요
/*
음식 종류별로 즐겨찾기가 가장 많은..
*/

SELECT  I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM REST_INFO I
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ) S ON I.FOOD_TYPE = S.FOOD_TYPE AND I.FAVORITES = S.FAVORITES
ORDER BY I.FOOD_TYPE DESC