WITH CATEGORY_FAVORITES AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) 
SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM REST_INFO I
JOIN CATEGORY_FAVORITES F ON I.FOOD_TYPE = F.FOOD_TYPE AND I.FAVORITES = F.MAX_FAVORITES
ORDER BY I.FOOD_TYPE DESC














-- SELECT  I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
-- FROM REST_INFO I
-- JOIN (
--     SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
--     FROM REST_INFO
--     GROUP BY FOOD_TYPE
--     ) S ON I.FOOD_TYPE = S.FOOD_TYPE AND I.FAVORITES = S.FAVORITES
-- ORDER BY I.FOOD_TYPE DESC