-- 코드를 입력하세요
/*
중고 거래 게시물 3건 이상 등록
*/
WITH MORE_THEN_THREE AS (
    SELECT WRITER_ID, COUNT(*) AS CNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
    )
    
-- SELECT *
-- FROM MORE_THEN_THREE

SELECT 
    U.USER_ID,
    U.NICKNAME,
    U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2 AS 전체주소,
    SUBSTR(U.TLNO, 1, 3) || '-' || SUBSTR(U.TLNO, 4, 4) || '-' || SUBSTR(U.TLNO, 8) AS TLNO
FROM USED_GOODS_USER U
JOIN MORE_THEN_THREE T 
    ON U.USER_ID = T.WRITER_ID
ORDER BY U.USER_ID DESC;