/*
서울에 위치한
평균 점수를 반올림
*/
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, SCORE
FROM REST_INFO I
JOIN (
    SELECT F.REST_ID, ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
    FROM REST_INFO F
    JOIN REST_REVIEW R ON F.REST_ID = R.REST_ID
    WHERE F.ADDRESS LIKE '서울%'
    GROUP BY F.REST_ID
    ) S ON I.REST_ID = S.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC 










-- -- 코드를 입력하세요
-- SELECT
--     I.REST_ID,
--     I.REST_NAME,
--     I.FOOD_TYPE,
--     I.FAVORITES,
--     I.ADDRESS,
--     R.SCORE
-- FROM
--     REST_INFO I
-- JOIN (
--     SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
--     FROM REST_REVIEW
--     GROUP BY REST_ID
-- ) R ON I.REST_ID = R.REST_ID
-- WHERE I.ADDRESS LIKE '서울%'
-- ORDER BY SCORE DESC, I.FAVORITES DESC