-- 코드를 입력하세요
/*
서울에 위치한 식당

*/
# SELECT REST_ID,REST_NAME,FOOD_TYPE,FAVORTIES,ADDRESS,SCORE
# FROM REST_INFO I
# JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
# WHERE ADDRESS LIKE '서울%'

# SELECT REST_ID, AVG(REVIEW_SCORE) AS SCORE
# FROM REST_REVIEW R
# GROUP BY REST_ID

SELECT
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    R.SCORE
FROM
    REST_INFO I
JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, I.FAVORITES DESC