-- 코드를 입력하세요
/*
년,월,성별 별로 상품을 구매한 회원수 집계

JOIN OR LEFT JOIN
*/
SELECT 
    EXTRACT(YEAR FROM S.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM S.SALES_DATE) AS MONTH,
    I.GENDER,
    COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO I JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM S.SALES_DATE), EXTRACT(MONTH FROM S.SALES_DATE), GENDER
ORDER BY EXTRACT(YEAR FROM S.SALES_DATE), EXTRACT(MONTH FROM S.SALES_DATE), GENDER