-- 코드를 입력하세요
/*
대여 시작일이 22년 9월, 대여 기간이 30일 이상
*/
SELECT HISTORY_ID, CAR_ID,
    TO_CHAR(START_DATE,'YYYY-MM-DD'),
    TO_CHAR(END_DATE,'YYYY-MM-DD'),
    CASE WHEN END_DATE - START_DATE +1 >=30 THEN '장기 대여'
    ELSE '단기 대여' 
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN DATE '2022-09-01' AND DATE '2022-09-30'
ORDER BY HISTORY_ID DESC