-- 코드를 입력하세요
/*
CAR ID 평균 대여기간이 7일 이상
7일 이상인 걸 어떻게 구할지? DATEDIFF 함수를 이용
ORACLE은 GROUP BY에서 SELECT 별칭이 적용 안되는 것 같음

*/
SELECT 
    CAR_ID,
    TO_CHAR(ROUND(AVG(END_DATE - START_DATE + 1), 1), 'FM999.0') AS AVERAGE_DURATION
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 
    CAR_ID
HAVING 
    ROUND(AVG(END_DATE - START_DATE + 1), 1) >= 7
ORDER BY 
    ROUND(AVG(END_DATE - START_DATE + 1), 1) DESC,
    CAR_ID DESC;

