-- 코드를 작성해주세요
/*
총 누계거리, 평균 역사이거리
*/
SELECT ROUTE,
    CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1),'km') AS TOTAL_DISTANCE, 
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE D
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC