-- 코드를 입력하세요
/*
2021년에 가입한 전체 회원중 상품 구매한 회원수와 상품을 구매한 회원의 비율
년,월 별로 출력
*/

WITH A AS (
    /* 2021년 가입자 */
    SELECT
        USER_ID
      FROM USER_INFO
     WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
)
, B AS (
    /* 2021년에 가입한 회원 중 상품을 구매한 회원수 */
    SELECT
        TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR
        , TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH
        , COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS
      FROM ONLINE_SALE S
      JOIN A
        ON A.USER_ID = S.USER_ID
  GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY')
           , TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM'))
)   
SELECT
    B.YEAR
    , B.MONTH
    , B.PURCHASED_USERS
    , ROUND(B.PURCHASED_USERS / COUNT(A.USER_ID), 1) AS PURCHASED_RATIO
  FROM A,B
 GROUP BY B.YEAR, B.MONTH, B.PURCHASED_USERS
 ORDER BY YEAR, MONTH