-- 코드를 입력하세요
WITH ALL_USER_2021 AS (
    SELECT COUNT(*) AS TOTAL_USERS
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
PURCHASES AS (
    SELECT 
        YEAR(S.SALES_DATE)  AS YEAR,
        MONTH(S.SALES_DATE) AS MONTH,
        COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS
    FROM USER_INFO I
    JOIN ONLINE_SALE S
      ON I.USER_ID = S.USER_ID
    WHERE YEAR(I.JOINED) = 2021
    GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
)
SELECT 
    P.YEAR,
    P.MONTH,
    P.PURCHASED_USERS,
    ROUND(P.PURCHASED_USERS / (AU.TOTAL_USERS * 1.0), 1) AS puchased_ratio
FROM PURCHASES P
CROSS JOIN ALL_USER_2021 AU
ORDER BY P.YEAR, P.MONTH;