-- 코드를 입력하세요
/*
2022년 10월16일에 대여중인 자동차
*/
SELECT CAR_ID, 
    CASE 
        WHEN EXISTS (
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            WHERE H.CAR_ID = C.CAR_ID
              AND '2022-10-16' BETWEEN START_DATE AND END_DATE
        ) THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) C
GROUP BY CAR_ID
ORDER BY CAR_ID DESC