-- 코드를 입력하세요
/*
생산일자가 22년 5월인 식품의 총 매출

PRODUCT_ID로 JOIN해서 YEAR = 2022 AND MONTH = 05? 
PRODUCT_ID 기준으로 GROUP BY 후에 PRODUCT_NAME을 보여준다 
*/
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (TOT * P.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOT
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE) = '05'
    GROUP BY PRODUCT_ID
    ) S ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY (TOT * P.PRICE) DESC, PRODUCT_ID ASC 