-- 코드를 입력하세요
/*
자동차 종류가 트럭인 자동차의 대여 기록에 대해서
대여 기록 별로 FEE를 구하기

DURATION을 구해서 DURATION_TYPE에 맞게 
*/
-- SELECT
--     H.HISTORY_ID
--     ,C.DAILY_FEE *
--     (H.END_DATE - H.START_DATE +1) * 
--     (100 - TO_NUMBER(REPLACE(P.DISCOUNT_RATE, '%', ''))) / 100 AS FEE,
--     CASE 
--         WHEN (H.END_DATE - H.START_DATE +1) >= 90 THEN '90일 이상'
--         WHEN (H.END_DATE - H.START_DATE +1) >= 30 THEN '30일 이상'
--         WHEN (H.END_DATE - H.START_DATE +1) >= 7 THEN '7일 이상'
--     END AS DURATION_TYPE
-- FROM CAR_RENTAL_COMPANY_CAR C
-- JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
-- ON C.CAR_ID = H.CAR_ID 
-- JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
-- ON DURATION_TYPE = P.DURATION_TYPE
-- WHERE C.CAR_TYPE = '트럭'

WITH RENTAL_DATA AS (
    SELECT 
        H.HISTORY_ID,
        C.DAILY_FEE,
        C.CAR_TYPE,
        CASE 
            WHEN (TRUNC(H.END_DATE) - TRUNC(H.START_DATE) + 1) >= 90 THEN '90일 이상'
            WHEN (TRUNC(H.END_DATE) - TRUNC(H.START_DATE) + 1) >= 30 THEN '30일 이상'
            WHEN (TRUNC(H.END_DATE) - TRUNC(H.START_DATE) + 1) >= 7  THEN '7일 이상'
            ELSE '7일 미만'
        END AS DURATION_TYPE,
        (TRUNC(H.END_DATE) - TRUNC(H.START_DATE) + 1) AS RENT_DAYS
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
        ON C.CAR_ID = H.CAR_ID 
    WHERE C.CAR_TYPE = '트럭'
)

SELECT 
    R.HISTORY_ID,
    TRUNC(
      R.DAILY_FEE * R.RENT_DAYS *
      (100 - NVL(TO_NUMBER(REPLACE(P.DISCOUNT_RATE, '%', '')), 0)) / 100
    ) AS FEE
FROM RENTAL_DATA R
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON R.DURATION_TYPE = P.DURATION_TYPE
    AND R.CAR_TYPE = P.CAR_TYPE 
ORDER BY FEE DESC, R.HISTORY_ID DESC
