-- SELECT (H.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL_ORDER, H.FLAVOR
-- FROM FIRST_HALF H
-- JOIN JULY J ON H.FLAVOR = J.FLAVOR
-- ORDER BY TOTAL_ORDER DESC
-- FETCH FIRST 3 ROWS ONLY

SELECT H.FLAVOR
FROM FIRST_HALF H
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J ON H.FLAVOR = J.FLAVOR
ORDER BY (H.TOTAL_ORDER + J.TOTAL_ORDER) DESC
FETCH FIRST 3 ROWS ONLY







-- SELECT H.FLAVOR
-- FROM FIRST_HALF H
-- JOIN (
--     SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOT
--     FROM JULY 
--     GROUP BY FLAVOR
--      ) S ON H.FLAVOR = S.FLAVOR
-- ORDER BY H.TOTAL_ORDER+S.TOT DESC
-- FETCH FIRST 3 ROWS ONLY