SELECT H.FLAVOR
FROM FIRST_HALF H
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOT
    FROM JULY 
    GROUP BY FLAVOR
     ) S ON H.FLAVOR = S.FLAVOR
ORDER BY H.TOTAL_ORDER+S.TOT DESC
FETCH FIRST 3 ROWS ONLY