-- 코드를 입력하세요
/*
0시부터 23시까지, 각 시간대별로 입양이 몇 건이나 발생했는지 조회
시간대 순으로 정렬해야 합니다.
*/
WITH TIMETABLE (HOUR) AS (
    SELECT 0 FROM DUAL
    UNION ALL
    SELECT HOUR + 1
    FROM TIMETABLE
    WHERE HOUR < 23
)

SELECT T.HOUR AS HOUR, COUNT(O.ANIMAL_ID) AS COUNT 
FROM TIMETABLE T
LEFT JOIN ANIMAL_OUTS O ON T.HOUR = TO_NUMBER(TO_CHAR(O.DATETIME, 'HH24'))
GROUP BY T.HOUR
ORDER BY T.HOUR ASC

/*
EXTRACT(HOUR FROM O.DATETIME) 
*/