-- 코드를 입력하세요
WITH RECURSIVE TIMETABLE (HOUR) AS (
    SELECT 0 FROM DUAL
    UNION ALL
    SELECT HOUR + 1
    FROM TIMETABLE
    WHERE HOUR < 23
)

SELECT T.HOUR AS HOUR, COUNT(O.ANIMAL_ID) AS COUNT 
FROM TIMETABLE T
LEFT JOIN ANIMAL_OUTS O ON T.HOUR = HOUR(O.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR ASC