-- 코드를 작성해주세요

 
WITH FRONT_SKILL AS(
    SELECT SUM(CODE) AS TOTAL_FRONT
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
FRONT_DEVELOPER AS (
    SELECT ID
    FROM DEVELOPERS, FRONT_SKILL
    WHERE SKILL_CODE & FRONT_SKILL.TOTAL_FRONT  > 0
)

SELECT D.ID, D.EMAIL, D.FIRST_NAME,D.LAST_NAME 
FROM DEVELOPERS D
JOIN FRONT_DEVELOPER F ON D.ID = F.ID 
ORDER BY D.ID ASC