-- 코드를 입력하세요
/*
완료된 중고 거래의 총 금액이 70만원 이상
*/
SELECT B.WRITER_ID AS USER_ID, sub.NICKNAME ,SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN (
    SELECT USER_ID, NICKNAME
    FROM USED_GOODS_USER
) sub 
    ON B.WRITER_ID = sub.USER_ID
WHERE STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC


