/*
2022년 8월부터 2022년 10월까지의 대여횟수가 5회이상인 자동차
해당 기간 동안의 월별 자동차 총 대여 횟수
*/
WITH CONDITION_ID AS (
   SELECT CAR_ID, COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5 
)

SELECT EXTRACT(MONTH FROM H.START_DATE) AS MONTH, I.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CONDITION_ID I ON H.CAR_ID = I.CAR_ID
WHERE H.START_DATE >= DATE '2022-08-01'
  AND H.START_DATE <  DATE '2022-11-01'
GROUP BY EXTRACT(MONTH FROM H.START_DATE),I.CAR_ID,I.RECORDS
ORDER BY EXTRACT(MONTH FROM H.START_DATE) ASC,I.CAR_ID DESC














-- SELECT 
--     EXTRACT(MONTH FROM START_DATE) AS MONTH,
--     CAR_ID,
--     COUNT(*) AS RECORDS
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31' AND CAR_ID IN (
--         SELECT CAR_ID
--         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--         WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
--         GROUP BY CAR_ID
--         HAVING COUNT(*) >= 5
--     )
-- GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
-- ORDER BY EXTRACT(MONTH FROM START_DATE) ASC, CAR_ID DESC;