-- 코드를 작성해주세요
/*
연도별로 최대 값을 뽑아낸다. 그 상태에서 
모든 행을 훑으면서 최대값 - 해당 행의 SIZE_OF_COLONY를 뺀다.

*/
SELECT 
  YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
  (m.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV,
  e.ID
FROM ECOLI_DATA e
JOIN (
  SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
  FROM ECOLI_DATA
  GROUP BY YEAR(DIFFERENTIATION_DATE)
) m
  ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC