-- 코드를 작성해주세요
/*
BASS와 SNAPPER의 수를 출력
*/

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_NAME_INFO
    WHERE FISH_NAME IN ('BASS', 'SNAPPER')
    )
-- LENGTH IS NOT NULL AND