-- 코드를 입력하세요
/*
'세단' + 10월에 대여를 시작한 기록이 있는..
ID 중복 없이
*/
SELECT DISTINCT(C.CAR_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단' AND H.START_DATE BETWEEN DATE '2022-10-01' AND DATE '2022-10-31'
ORDER BY C.CAR_ID DESC
