-- 코드를 작성해주세요
SELECT ID,NI.FISH_NAME,LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO NI
ON I.FISH_TYPE = NI.FISH_TYPE
WHERE (I.FISH_TYPE, I.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO F
    GROUP BY FISH_TYPE
    )
ORDER BY I.ID ASC

# JOIN FISH_NAME_INFO I
# ON F.FISH_TYPE = I.FISH_TYPE
# GROUP BY FISH_NAME