-- 코드를 작성해주세요
# SELECT ID,NI.FISH_NAME,LENGTH
# FROM FISH_INFO I
# JOIN FISH_NAME_INFO NI
# ON I.FISH_TYPE = NI.FISH_TYPE
# WHERE (I.FISH_TYPE, I.LENGTH) IN (
#     SELECT FISH_TYPE, MAX(LENGTH)
#     FROM FISH_INFO F
#     GROUP BY FISH_TYPE
#     )
# ORDER BY I.ID ASC

SELECT I.ID, NI.FISH_NAME, S.LENGTH
FROM FISH_INFO I
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    ) S  ON I.FISH_TYPE = S.FISH_TYPE AND I.LENGTH = S.LENGTH
JOIN FISH_NAME_INFO NI ON I.FISH_TYPE = NI.FISH_TYPE
ORDER BY I.ID ASC