-- 코드를 작성해주세요
/*
부서별 평균 연봉
GROUP BY에 있는 컬럼만 SELECT 가능하다
*/

SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(AVG(E.SAL),0) AS AVG_SAL
FROM HR_DEPARTMENT D
JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
GROUP BY DEPT_ID, DEPT_NAME_EN
ORDER BY AVG_SAL DESC