SELECT P.CATEGORY, MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    ) S ON P.CATEGORY = S.CATEGORY AND P.PRICE = MAX_PRICE
WHERE P.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY MAX_PRICE DESC